### PR TITLE
Update GreenCharterProposal.md

### PR DESCRIPTION
**Pull request by emile22**
very short term parsable string

### CODE REVIEW

**Review by marisolpalmero — COMMENTED** [review]
@emile22, we should rephrase as "sustainability" should not considered as part of the BOF proposal

**Comment by tlwr** [comment]
> Start by documenting a parsable string giving the minimum information about the parts of a legacy device which migrated to sustainability

to become

> Produce guidance for vendors on how to expose information from legacy devices which have been upgraded with more energy efficient components

?

**Comment by emile22** [comment]
I suggest:
Start by producing guidance for vendors on how to expose information from legacy devices about the parts which have been upgraded with more energy efficient components

**Comment by tlwr** [comment]
Good suggestion 👍

**Review by marisolpalmero — COMMENTED** [review]
I will rephrase as confirmed with Emile:
"Start by producing guidance for vendors on how to expose information from legacy devices about the parts which have been upgraded with more energy efficient components".

**Comment by marisolpalmero** [comment]
I will close this pull request without any changes, and include this line as part of the Green Charter focus:
"Start by producing guidance for vendors on how to expose information from legacy devices about the parts which have been upgraded with more energy efficient components"

**Pull request closed without merging**
