### PR TITLE
Change proposed WG name

### PR DESCRIPTION
**Pull request by billwuqin**
Marisol, I think Adrian's proposed WG name change, make sense, what do you think?

### CODE REVIEW

**Comment by marisolpalmero** [comment]
I would prefer to wait for the group meeting tomorrow, before agreed on working group name.

**Comment by dhruvdhody** [comment]
I like the name change proposed by Adrian!

**Comment by snmitrov** [comment]
I also like the proposed name change!

**Comment by marisolpalmero** [comment]
name changed as reqeusted for the WG

**Pull request merged**
